# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5dd321bf4de83eecf1ef6d628bf13517"
name = "Checkout Functionality"
handle = "checkout-functionality"
application_url = "https://teacher-explained-pensions-teen.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "habitt-international-mean3.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://teacher-explained-pensions-teen.trycloudflare.com/auth/callback",
  "https://teacher-explained-pensions-teen.trycloudflare.com/auth/shopify/callback",
  "https://teacher-explained-pensions-teen.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
